#!/bin/bash

container=$1
target=$2

volumes=$(docker inspect --format "{{ range \$key,\$value := .Config.Volumes}} {{ \$key }} {{ end }}" $container)
for volume in $volumes; do
    echo docker cp $container:$volume $target
    docker cp $container:$volume $target
done
